import React from "react"
import alexP from '../images/alex512.jpg'
import Layout from "../components/layout"
import Video from '../components/video'
import Share from '../components/share'
import {TwitterTweetEmbed} from 'react-twitter-embed';
const alex = () => (
  <Layout>
    <h1 className='h1-title'>Why twitter banned Alex Jones - nuanced arguments from both sides</h1>
    <p className='date'><i>Apr 11, 2019</i></p>
    <img src={alexP} alt='Alex Jones'/>
    <p>Alex Jones is an American radio show host and conspiracy theorist. In Aug 2018, Jones was removed from itunes podcast directory. Facebook, spotify and youtube also took immediate action. This sparked huge controversy. People on one side of the <i>cultural divide</i> believe private corporations have the right to kick people out of their platforms and social media companies are similar to <i>publishers</i> in that they are responsible for their content. They may or may not agree with policing hate speech, but they do agree inciting abuse against people which transforms into real life harassment and threat is off limits. Specifically, Jones spread misinformation that Sandy Hook parents were crisis actors in a government conspiracy to take away people’s guns. A Jones devotee Lucy Richards was sentenced to five months in prison for threatening the life of Leonard Pozner, whose 6-year-old son was killed in Sandy Hook shooting.</p>
    <p>People on the other side of the cultural divide believe it is a slippery slope for social media companies to dictate people’s speech. They argue hate speech is hard to define and are sceptical of leaving that power to a handleful of liberal elites at giant tech companies. They believe social media companies are similar to a <i>platform</i>, in that they are providing utility and service for its users. A higher proportion believe hate speech should not be regulated, although they do agree hate speech that transforms into threats in real life should be. Some argue Jones should not be held accountable for the misbehaviour of his followers given the size of his follower base.</p>
    <p>Amidst the domino of bannings against Jones, twitter adopted a unique position. Despite immense pressure from other tech giants, to twitter’s credit, or some's disappointment, twitter did not follow its peers at the time. According to twitter CEO Jack Dorsey, "Alex Jones and infowars didn’t violate our rules”. Jones was eventually banned from twitter for different reasons.</p>
    <p>The official reason twitter banned Jones was presented by Vijaya Gadde, global lead for legal, policy, and trust and safety at Twitter, on Joe Rogan’s podcast. She explained twitter's three-strike concept, where user will be banned after three violations of twitter rules. She quoted three videos that got Jones banned. By providing links to the videos, it <strong>does not in any way, shape or form means the endorsement of the content of those videos or the uploader</strong>.</p>
    <p>The first <a className="p-link"href="https://www.infowars.com/cnn-lies-about-banned-infowars-videos-in-new-censorship-attempt/#2" rel="noopener noreferrer" target="_blank">video</a> is titled “How To Prevent Liberalism - A Public Service Announcement“, that shows a boy being thrown to the ground by a grown man and crying. Info wars argued "it is a humorous commentary on how cry-bullies on the left constantly claim to be the victims while violently attacking other people". The video was meant to trigger and mock liberal snowflakes. However, twitter viewed it as child endangerment because the man shoved the boy to the ground and the boy was clearly in pain. It assumes Jones wishes harm for the child and others. It is fascinating to see the cultural divide through this video alone. One side sees the <i>symbolism</i>, the other side sees the <i>literal</i>.</p>
    <p>The second video that Gadde quoted is the video that Jones posted on periscope (streaming app that twitter owns), that twitter viewed as inciting violence against mainstream media. Below is the transcript.</p>
    <Video videoSrcURL="https://www.youtube.com/embed/w09zl8iZP3I" videoTitle="alex jones" />
    <p>“You pointed out mainstream media is the enemy. But now it’s time to act on the enemy before they do a false flag. I know the justice department crippled a bunch of followers and cowards, but there’s groups, there’s grand jury, there’s you call for it, it’s time politically, economically, judiciously, legally and criminally to move against these people. It’s got to be done now. Get together people you know aren’t traitors, aren’t cowards, aren’t hedging their freaking bets like all these other assholes do and let’s go, let’s do it, because they are coming. In your wisdom, you may be playing the possum and wait before them to come in, but America needs to know, that they’ve got their little pathetic commie red teams ready, and they got their targets picked out, the sheriffs, the judges, the police chiefs, the patriots, the veterans, the talk show hosts, and everyone’s gotta be amazed when they come, when those cowards come, it’s gonna hit at the middle of the night and they are coming. They think they can really take down America. This is it. So people need to have their battle rifles ready, and everything ready at their bedside. And you gotta be ready because media is so disciplinary in their deception. Antifa attacked all these people at the white house, beat up reporters, beat up women and children, no coverage, they got discipline folks, they got criminal discipline because they are a bunch of followers.”
</p>
    <p>People on one side of the cultural divide view the words “have their <i>battle rifles ready</i>” and “time to act on the enemy” as direct calls to violence against the mainstream media. When online hate transforms into real life, his rhetoric has gone too far, in that it has gone beyond what freedom of speech grants him. People on the other side believe Jones was ranting on mainstream media’s biased reporting of antifa and didn’t mean literal violence against reporters. They believe Jones was warning people of rising communist influence in America and encouraged people to bear arms.</p>
    <Video videoSrcURL="https://www.youtube.com/embed/Y5ecxkYYm3A" videoTitle="confront" />
    <p>The third video Gadde quoted is his verbal altercation with CNN journalist Oliver Darcy outside of a congressional hearing of twitter CEO Jack Dorsey in Capitol Hill. Gadde picked out certain keywords that convinced twitter that Jones was engaging in harassment.</p>
    <p>“Eyes of the rat, evil looking person, just scum, virus to America and freedom, smelling like a possum that climbed out of the rear end of a dead cow, look like a possum that got caught doing some really really nasty stuff in my view.”</p>
    <p>People on one side of the cultural debate think these are somewhat funny and simply mean things to say. They think words do not cause harm. People should be allowed to say mean things or even hateful speech as long as they do not harm people’s physical safety. People also have the right to confront other people. People on the other side also share these values, but they think these words qualify as harassment in the context of two other incidents. Jones confronted Florida senator Marco Rubio, he also yelled at Dorsey at one point as he was leaving the building. These incidents combined established a pattern and practice of targeted harassment. Gadde mentioned her team does not only look at one video, she views it in the context of other videos and made the decision.</p>
    <Video videoSrcURL="https://www.youtube.com/embed/wuC2tdSPMVg" videoTitle="marco" />
    <p>To address some of the questions, “is twitter banning Alex Jones because he is conservative?” Highly unlikely. If twitter were to ban Jones for that reason, it would have followed its peers in banning him straight away. As a matter of fact, twitter got a lot of heat for not doing that, including from former reddit CEO Ellen Pao, “Your move, @jack. Be a leader with integrity like @tim_cook”.</p>
    <TwitterTweetEmbed tweetId={'1026984242893357056'}/>
    <p>However, it is a completely different debate when it comes to “is twitter censoring people because they are conservatives?” The reason is it will touch on shadow banning, also people are different, and they get banned for different reasons. Since a more specific question is easier to answer, we only discuss Jones in this article.</p>
    <p>There is contentious debate on the <i>partiality</i> of the rules. There is a sentiment on the center and right that the rules do not apply / apply less to the left. Independent journalist Tim Pool mentioned during Joe Rogan’s podcast that twitter ignored his report of certain tweet threatening him while he was visiting Berkeley, but twitter took immediate action on tweet calling him a homosexual. This highlights the possible selective enforcement of rules regarding harassment, and implicit social justice agenda by twitter.</p>
    <p>To end off on a light note, there are also instances in which rules are enforced in <i>arbitrary</i> standards. Twitter banned a tweet because it incites hatred against elves. Fenris is a fictional character from video game Dragon Age. Fenris is an elf and slave in the video game. Apparently twitter’s algorithm mistook words "Fenris is an elven slave" in video game context as hatred in real life.</p>
    <TwitterTweetEmbed tweetId={'1013719738277683201'}/>
    <p>For the record, thetruthspace characterizes Joe Rogan and Tim Pool as being on the political left or center. People on the left who threaten others do not represent mainstream left, people on the right who threaten others do not represent mainstream right.</p>
    <Share url="www.google.com" title="Why twitter banned Alex Jones - nuanced arguments from both sides"/>
  </Layout>
)

export default alex
