import React from "react"
import miloTweet from '../images/fake.png'
import miloP from '../images/milo256copy.jpg'
import Layout from "../components/layout"
import wood from '../images/woodchipper.jpg'
import Share from '../components/share'

const milo = () => (
  <Layout>
    <h1 className = 'h1-title'>Why twitter banned Milo Yiannopoulos - the cultural implications</h1>
    <p className='date'><i>Apr 11, 2019</i></p>
    <img src={miloP} alt='milo' title='Milo Yiannopoulos'/>
    <p>Milo Yiannopoulos is a British political commentator, former editor for Breitbart News. He is a provocateur and no stranger to controversy. Yiannopoulos was banned from twitter in July 2016 for harassing comedian and actress Leslie Jones for the role she played in the movie Ghostbusters. Vijaya Gadde, global lead for legal, policy, and trust and safety at Twitter, recently disclosed the official reason twitter banned Milo, on Joe Rogan’s podcast. Yiannopoulos had a number of tweets that violated twitter’s rules going back to 2014. There are three major incidents that caused his account getting banned. </p>
    <p>The first incident is Yiannopoulos claimed to be a buzzfeed "social justice editor" in his twitter bio in December 2015. His account was temporarily suspended and his blue verification checkmark was removed. According to Gadde, what Yiannopoulos did is considered <i>impersonation</i>, which is a violation of the Twitter Rules. When Rogan postulated the possibility of Yiannopoulos doing <i>parody</i>, Gadde responded, "if you are doing parody, you must mention it is a parody account".</p>
    <p>It is interesting to see the <i>cultural divide</i> in this incident alone. People on one side think that there is great sarcasm in Yiannopoulos being an anti PC figure, claiming to be a buzzfeed social justice reporter. Combined with the fact that Yiannopoulos is well known, people should not be misled about his identity. His intention is not to impersonate, but make a mockery. People on the other side think that Yiannopoulos is impersonating a buzzfeed reporter. No matter how well known he is, there are bound to be people who didn’t know Yiannopoulos before and was misled into believing it. He should have issued a disclaimer, otherwise the action of impersonation should be punished regardless of intention.</p>
    <p>The second incident is <i>doxxing</i>, which means publishing private information about an individual. Gadde mentioned Yiannopoulos doxxed someone but did not disclose the exact detail. According to Twitter CEO Jack Dorsey, twitter's primary focus is users' physical safety and needs to be “proactive” at going after doxxing. Any reasonable person on the left and right would agree because doxxing may lead to endangerment of physical safety. This is one of the rare cases <i>both sides agree</i> that twitter has a legitimate reason to regulate its content.</p>
    <p>The third incident is "inciting or engaging in the <i>targeted abuse or harassment</i> of others". Gadde mentioned Yiannopoulos tweeted to someone, "if you were my child, I would have dashed your head on a rock and try it again".</p>
    <p>Yiannopoulos also posted things that are viewed by twitter as incitement of abuse against comedian and actress Leslie Jones in July 2016. He posted two doctored (fake) tweets that are supposedly by Leslie Jones to make her look bad.</p>
    <img src={miloTweet} alt='miloTweet'/>
    <p>When other twitter users pointed out to Yiannopoulos those tweets may be fake, he tweeted "Don’t tell me some mischievous internet rascal made them up!" He also described Jones as "Barely literate" and then called her a "black dude". These tweets plus the fact that hundreds of anonymous Twitter trolls motivated by Yiannopoulos hurled racist and sexist remarks at Jones’ Twitter account convinced twitter that Yiannopoulos is engaging in coordinated behaviour and inciting people to attack Leslie Jones.</p>
    <p>It is interesting to see what Joe Rogan’s said about Yiannopoulos. “It all stemmed from Milo’s <i>legitimate criticism</i> of the film” Ghostbusters, in which Leslie Jones is a star. “Milo is a satirist and he is mocking the film”. It is not obvious whether Rogan is defending Yiannopoulos or playing devil’s advocate, but it’s fascinating to see both sides of the story. People on one side of the cultural debate think Ghostbusters has a feminist/SJW agenda. They are willing to get behind Yiannopoulos and join the <i>troll army</i> and write off some of his offensive tweets. They think people with huge followings should not be accountable for their fans' behaviour. People on the other side think Yiannopoulos is <i>perpetuating hate</i> and using his influence to <i>incite abuse</i> against Jones, who is a black woman. They think Yiannopoulos was encouraging his base, thus was responsible.</p>
    <p>To address the question, “is twitter banning Milo Yiannopoulos because he is conservative?” According to official reasons given by Gadde, Yiannopoulos clearly violated twitter’s rules three times. Based on twitter’s “three strike concept”, accounts with three strikes will be removed.</p>
    <p>However, some argue twitter’s rules may have an <i>implicit ideological bias</i>, thus was unfair to Yiannopoulos. They argue twitter may be <i>partial</i> at applying its rules on hate speech and harassment depending on which side they are from. One example Rogan gave was a tweet by Disney producer Jack Morrissey who called for violence against Covington kids.</p>
    <p>“#MAGA (trump supporting) kids go screaming, hats first, into the woodchipper.”</p>
    <img src={wood} alt="child"/>
    <p>Twitter did not ban that tweet (later deleted) that threatens children, but gave a strike to Yiannopoulos’ tweets to Jones. This may be seens as an example of twitter’s liberal bias.</p>
    <p>The other side argues not banning hateful tweets from the left is a <i>mistake</i>, not due to twitter’s ideology or bias. Twitter bannings operate on algorithms and user report, and algorithms make mistakes. Regarding user report, it may be the case that the left more often reports hateful tweets from the right, but the right reports the left less often. Disclaimer: this point needs further substantiation. Since twitter receives more complaints against the right, it ends up creating the impression that twitter is only banning the right, but less on the left.</p>
    <p>No matter what the reasons are, “grains of sand makes a heap”. If the perception that twitter is banning more conservatives persists, at some point, people will question twitter’s motives.</p>
    <p>Again, to answer the question, “is twitter banning Milo because of his conservative beliefs?” Likely not, but the jury is still out. Twitter’s strikes on Yiannopoulos based on impersonation and doxxing still stand. The strike on harassment of Jones may be up for debate, with the reasons presented above.</p>
    <p>Ultimately, Twitter has an incredibly difficult job at regulating content on its platform. Some tweets are censored based on algorithms, which may make mistakes, some are censored based on people reporting on those tweets. According to independent journalist Tim Pool, he generalized that “[some of] the left wants more censorship, [some of] the right wants less”. No matter what actions twitter takes, the social media giant is going to be criticized.</p>
    <Share url="www.thetruspace.com/TwitterBansYiannopoulos" title="Why twitter banned Milo Yiannopoulos - the cultural implications"/>
  </Layout>
)

export default milo
